/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	alpha1 "github.com/lichangjiang/iperf-operator/pkg/apis/iperf.test.svc/alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIperfTasks implements IperfTaskInterface
type FakeIperfTasks struct {
	Fake *FakeIperfAlpha1
	ns   string
}

var iperftasksResource = schema.GroupVersionResource{Group: "iperf.test.svc", Version: "alpha1", Resource: "iperftasks"}

var iperftasksKind = schema.GroupVersionKind{Group: "iperf.test.svc", Version: "alpha1", Kind: "IperfTask"}

// Get takes name of the iperfTask, and returns the corresponding iperfTask object, and an error if there is any.
func (c *FakeIperfTasks) Get(name string, options v1.GetOptions) (result *alpha1.IperfTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(iperftasksResource, c.ns, name), &alpha1.IperfTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alpha1.IperfTask), err
}

// List takes label and field selectors, and returns the list of IperfTasks that match those selectors.
func (c *FakeIperfTasks) List(opts v1.ListOptions) (result *alpha1.IperfTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(iperftasksResource, iperftasksKind, c.ns, opts), &alpha1.IperfTaskList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &alpha1.IperfTaskList{ListMeta: obj.(*alpha1.IperfTaskList).ListMeta}
	for _, item := range obj.(*alpha1.IperfTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iperfTasks.
func (c *FakeIperfTasks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(iperftasksResource, c.ns, opts))

}

// Create takes the representation of a iperfTask and creates it.  Returns the server's representation of the iperfTask, and an error, if there is any.
func (c *FakeIperfTasks) Create(iperfTask *alpha1.IperfTask) (result *alpha1.IperfTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(iperftasksResource, c.ns, iperfTask), &alpha1.IperfTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alpha1.IperfTask), err
}

// Update takes the representation of a iperfTask and updates it. Returns the server's representation of the iperfTask, and an error, if there is any.
func (c *FakeIperfTasks) Update(iperfTask *alpha1.IperfTask) (result *alpha1.IperfTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(iperftasksResource, c.ns, iperfTask), &alpha1.IperfTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alpha1.IperfTask), err
}

// Delete takes name of the iperfTask and deletes it. Returns an error if one occurs.
func (c *FakeIperfTasks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(iperftasksResource, c.ns, name), &alpha1.IperfTask{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIperfTasks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(iperftasksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &alpha1.IperfTaskList{})
	return err
}

// Patch applies the patch and returns the patched iperfTask.
func (c *FakeIperfTasks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *alpha1.IperfTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(iperftasksResource, c.ns, name, pt, data, subresources...), &alpha1.IperfTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alpha1.IperfTask), err
}
