apiVersion: iperf.test.svc/alpha1
kind: IperfTask
metadata: 
  name: my-iperf
  namespace: iperf-operator
spec:
  iperfImage: 172.17.8.101:30002/networkstatic/iperf3
  toEmail: 305120108@qq.com
  serverSpec:
    port: 9000
  clientSpec:
    interval: 1
    duration: 2
