apiVersion: iperf.test.svc/alpha1
kind: IperfTask
metadata: 
  name: my-iperf
  namespace: iperf-operator
spec:
  iperfImage: networkstatic/iperf3
  toEmail: YOUR_RECEIVE_EMAIL
  serverSpec:
    port: 9000
  clientSpec:
    mode: "fast"
    parallel: 1
    interval: 2
    duration: 10
