apiVersion: iperf.test.svc/alpha1
kind: IperfTask
metadata: 
  name: my-udp-iperf
  namespace: iperf-operator
spec:
  iperfImage: networkstatic/iperf3
  toEmail: YOUR_RECEIVE_EMAIL
  serverSpec:
    port: 9000
  clientSpec:
    udp: true
    bwLimit "1000M"
    mode: "fast"
    interval: 10
    duration: 60

