/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package alpha1

import (
	time "time"

	iperftestsvcalpha1 "github.com/lichangjiang/iperf-operator/pkg/apis/iperf.test.svc/alpha1"
	versioned "github.com/lichangjiang/iperf-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/lichangjiang/iperf-operator/pkg/client/informers/externalversions/internalinterfaces"
	alpha1 "github.com/lichangjiang/iperf-operator/pkg/client/listers/iperf.test.svc/alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IperfTaskInformer provides access to a shared informer and lister for
// IperfTasks.
type IperfTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() alpha1.IperfTaskLister
}

type iperfTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIperfTaskInformer constructs a new informer for IperfTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIperfTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIperfTaskInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIperfTaskInformer constructs a new informer for IperfTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIperfTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IperfAlpha1().IperfTasks(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IperfAlpha1().IperfTasks(namespace).Watch(options)
			},
		},
		&iperftestsvcalpha1.IperfTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *iperfTaskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIperfTaskInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iperfTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&iperftestsvcalpha1.IperfTask{}, f.defaultInformer)
}

func (f *iperfTaskInformer) Lister() alpha1.IperfTaskLister {
	return alpha1.NewIperfTaskLister(f.Informer().GetIndexer())
}
